name: Python Build

on: [push]
# on:
#   schedule:
#     - cron: "*/30 * * * *"
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        USER_ID: ${{ secrets.STUDENT_ID }}
        PASSWORD: ${{ secrets.STUDENT_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          # Installing Python Pip Dependencies
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Running Get Json
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python get_jsons.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          [[ -z $(git status -uno --porcelain) ]] && echo "No updates detected, no need for push" && exit 0;
          git commit -m "Updated timetable"
          git push