name: Python Build

on: [push]
# on:
#   schedule:
#     - cron: "*/30 * * * *"
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        USER_ID: ${{ secrets.STUDENT_ID }}
        PASSWORD: ${{ secrets.STUDENT_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
      - uses: nanasess/setup-chromedriver@master
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          # Installing Python Pip Dependencies
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Running Get Json
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python get_jsons.py