name: Python Build

on: [push]
# on:
#   schedule:
#     - cron: "*/30 * * * *"
#   workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        env:
          USER_ID: ${{ secret.STUDENT_ID }}
          PASSWORD: ${{ secret.STUDENT_PASSWORD}}
      - name: Install dependencies
        run: |
          # Installing ChromeDriver
          sudo apt update
          sudo apt install -y unzip xvfb libxi6 libgconf-2-4 
          sudo apt install default-jdk 
          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add 
          sudo bash -c "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list" 
          sudo apt -y update 
          sudo apt -y install google-chrome-stable 
          wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip 
          unzip chromedriver_linux64.zip 
          sudo mv chromedriver /usr/bin/chromedriver 
          sudo chown root:root /usr/bin/chromedriver 
          sudo chmod +x /usr/bin/chromedriver 
          # Installing Python Pip Dependencies
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python get_jsons.py